# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: trusty
sudo: false
language: python
python:
    - "3.6"

cache:
    pip: true

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/bundles/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

install:
  - pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme

script:
  # - pylint nonblocking_timer.py
  # - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - python -m unittest discover -p *_test.py
  - circuitpython-build-bundles --filename_prefix circuitpython-nonblocking_timer --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html
